# Generated by Django 5.2.5 on 2025-09-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
    ]
