# Generated by Django 5.2.5 on 2025-09-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklevel',
            name='risk_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
