# Generated by Django 5.2.5 on 2025-09-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_remove_customuser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='daily_assessment_data',
            new_name='weekly_assessment_data',
        ),
    ]
