# Generated by Django 5.2.5 on 2025-09-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_risklevel_risk_label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='riskchart',
            unique_together={('sex', 'age_group', 'smoker_status', 'bmi_group', 'sbp_group')},
        ),
    ]
