# Generated by Django 5.2.5 on 2025-09-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_alter_result_recommendation_delete_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientintakerecord',
            name='central_adiposity',
        ),
        migrations.RemoveField(
            model_name='patientintakerecord',
            name='obesity',
        ),
        migrations.RemoveField(
            model_name='patientintakerecord',
            name='raised_bp',
        ),
        migrations.RemoveField(
            model_name='patientscreening',
            name='possible_angina_heart_attack',
        ),
        migrations.RemoveField(
            model_name='patientscreening',
            name='possible_stroke_tia',
        ),
    ]
